@startuml CursoVirtual
Class User{
    
}
Class Student{

}

class Admin{

}

Class Course{

}

Class Module{

}

Class Lesson{

}

Class Content{

}

Class Teacher{

}


''Patron Observer
Interface Observer{
    +update(notification: Notification)

}

Interface Subject{
    +registerObserver(o: Observer)
    +removeObserver(o: Observer)
    +notifyObservers()

}

'' Patron Iterator
interface Iterator{
    +hasNext(): boolean
    +next(): Object

}

Class IteratorModule{


}

class IteratorLesson{

}

Interface Aggregate{
    +createIterator(): Iterator

}


'' Singleton
Class CourseManager{
    -instance: CourseManager {static}
    -CourseManager()
    +getInstance(): CourseManager {static}
    +CreateCurse(name: String): Course
    
}







'' Relaciones
User <|-- Student
User <|-- Teacher
User <|-- Admin
Course "1" *-- "0..*" Module
Module "1" *-- "0.." Content
Content "1" *-- "0.." Lesson
Course "1" o-- "0..*" Teacher
Course "1" o-- "0..*" Student

'' Patron Iterator
Aggregate -->  Iterator :create
Course ..|> Aggregate  : implements
IteratorModule ..|> Iterator : implements
IteratorLesson ..|> Iterator : implements


'' Patron Observer
Student ..|> Observer
Content ..|> Subject
Subject --> Observer

''patron Singleton
CourseManager ...> Course : creates
Admin ..> CourseManager : uses



@enduml